### ISSUE TITLE
Missing references in master branch

### ISSUE THREAD

**Issue by SujaySKumar** [facebook/duckling#459] opened 2020-03-05 10:39 UTC
Facing this issue with the latest duckling master:

`(.text+0xa1): undefined reference to ducklingzm0zi1zi6zi1zmFuuoxNkK08bIA0dGJuhBV1_DucklingziNumeralziESziVEziRules_rules_closure /home/ubuntu/mozart/duckling/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/libHSduckling-0.1.6.1-FuuoxNkK08bIA0dGJuhBV1.a(ES.o): In function cF7qi_info:`

```
Warning: The following modules should be added to exposed-modules or other-modules in /home/ubuntu/user/duckling/duckling.cabal:
             - In lib:
                 Duckling.Numeral.ES.AR.Rules
                 Duckling.Numeral.ES.CL.Rules
                 Duckling.Numeral.ES.CO.Rules
                 Duckling.Numeral.ES.ES.Rules
                 Duckling.Numeral.ES.MX.Rules
                 Duckling.Numeral.ES.PE.Rules
                 Duckling.Numeral.ES.VE.Rules
```

_Originally posted by @SujaySKumar in https://github.com/facebook/duckling/issues/189#issuecomment-595155236_

**Comment by haoxuany** [comment] 2020-03-06 00:23
This appears to be a duplicate of #458 unfortunately. I'll close this for now, but please let me know if this is not the case. :)

**Closed by haoxuany** 2020-03-06 00:23 UTC
