### ISSUE TITLE
Duckling not extrcted month span correctly 

### ISSUE THREAD

**Issue by SachinNarkhede** [facebook/duckling#304] opened 2018-12-24 06:36 UTC
Hello,

I have done to date implementation, but I am facing issue when I passed sentence "show balances for this month" or "show balances this month" duckling extract only one date but if i passed  sentence "show balances by this month" then extract two date its correct

show balanced dashboatrd
Showing balance dashboard. DATA={"pageInstanceId": "balance_dashboard", "slots": {"amount": null, "balance_widget_type": null, "beneficiary_account": null, "country": null, "currency": null, "from_date": null, "groupby": null, "ordering_bank": null, "ordering_party": null, "ordinal": null, "requested_slot": null, "submit_confirm": null, "time": null, "to_date": null, "view_type": null}}127.0.0.1 - - [2018-12-24 11:51:19] "POST /webhooks/rest/webhook?stream=true&token= HTTP/1.1" 200 626 1.150054

show trend analysis for this month
Showing trend analysis for selected period. DATA={"pageInstanceId": "balance_dashboard", "slots": {"amount": null, "balance_widget_type": "trend analysis", "beneficiary_account": null, "country": null, "currency": null, "from_date": null, "groupby": null, "ordering_bank": null, "ordering_party": null, "ordinal": null, "requested_slot": null, "submit_confirm": null, "time": "2018-12-01", "to_date": null, "view_type": null}}127.0.0.1 - - [2018-12-24 11:51:31] "POST /webhooks/rest/webhook?stream=true&token= HTTP/1.1" 200 667 1.113426

show trend analysis by this month
Showing trend analysis for selected period. DATA={"pageInstanceId": "balance_dashboard", "slots": {"amount": null, "balance_widget_type": "trend analysis", "beneficiary_account": null, "country": null, "currency": null, "from_date": "2018-12-01", "groupby": null, "ordering_bank": null, "ordering_party": null, "ordinal": null, "requested_slot": null, "submit_confirm": null, "time": {"to": "2018-12-01T00:00:00.000+01:00", "from": "2018-12-24T07:21:46.000+01:00"}, "to_date": "2018-12-24", "view_type": null}}127.0.0.1 - - [2018-12-24 11:51:47] "POST /webhooks/rest/webhook?stream=true&token= HTTP/1.1" 200 761 1.127874
![monthextractissue](https://user-images.githubusercontent.com/25879458/50392434-60043500-0774-11e9-8633-dbf05072e01d.PNG)

**Comment by chessai** [comment] 2021-05-25 22:22
Closing as duplicate of #306

**Closed by chessai** 2021-05-25 22:22 UTC
